name: Build gifski vendor bundle

on:
  push:
  pull_request:

jobs:
  build-bundle:
    runs-on: ubuntu-latest
    env:
      GIFSKI_VERSION: 1.5.0
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          ./build-bundle.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: gifski-bundle
          path: build/artifacts/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-bundle
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: gifski-bundle
          path: artifacts/
      - name: Generate checksums
        run: |
          cd artifacts
          sha256sum * > SHA256SUMS
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}